// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPvGlKuC0GRVBdAZQlnIg3H37JERwjJ0',
    appId: '1:557429013068:web:cb5ce7aa83cabd892792e9',
    messagingSenderId: '557429013068',
    projectId: 'dlauapp',
    authDomain: 'dlauapp.firebaseapp.com',
    storageBucket: 'dlauapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKkhnxxc_o0Too6WKtlnG6L2wKrBrGWM',
    appId: '1:557429013068:android:5d0f437aa0adaa142792e9',
    messagingSenderId: '557429013068',
    projectId: 'dlauapp',
    storageBucket: 'dlauapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYJHv3O8uPS9lxmxkUczVldQ5JaSsPos',
    appId: '1:557429013068:ios:a938d4cf1338cc0a2792e9',
    messagingSenderId: '557429013068',
    projectId: 'dlauapp',
    storageBucket: 'dlauapp.firebasestorage.app',
    iosBundleId: 'com.example.appDlau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPvGlKuC0GRVBdAZQlnIg3H37JERwjJ0',
    appId: '1:557429013068:web:04b84aa35262f5e32792e9',
    messagingSenderId: '557429013068',
    projectId: 'dlauapp',
    authDomain: 'dlauapp.firebaseapp.com',
    storageBucket: 'dlauapp.firebasestorage.app',
  );
}
